### ISSUE TITLE
diskrec debian wrong disk usage size

### ISSUE THREAD

**Issue by taropalo** [kronometrix/recording#113]
discrec reports partition (home)
Size 3G -> real 2.8G
Free 1G -> real 566M
%67 used -> real 79% used 

partition (tmp)
size 1G -> real 268M
free 1G -> real 237M
%0 used -> real 5% used

**Comment by sparvu** [comment]
here after changes:

 * home: 2.70 GB

 * tmp: 0.26 GB

 * root: 2.71 GB


I fixed diskrec to allow better and more precise reporting about Size GB, Free GB
