### ISSUE TITLE
Windows 10 rec reports wrong os

### ISSUE THREAD

**Issue by irimiab** [kronometrix/recording#59]
![image](https://cloud.githubusercontent.com/assets/2221542/9679320/59679a6a-52f6-11e5-8264-c1f66015e64b.png)

Windows 10 Pro x64 - it appears as **win8**

**Comment by sparvu** [comment]
will be taken care for 1.0.17

**Comment by sparvu** [comment]
Win32-0.52 has support for Windows 10, 2012 R2. I am updating now the perl library and it will be fixed in next release 1.0.17

**Comment by sparvu** [comment]
fixed in latest 1.0.17

**Comment by sparvu** [comment]
ATTN: not all Windows 10 versions are supported. Some will be still be reported as Windows 8
